name: Robot CI

on:
  push:
    branches: [ "feature/reportCI" ]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: local
      run: ls $GITHUB_WORKSPACE/AutomacaoWeb/tests/
    - name: Robot Framework - Tests
      run: robot $GITHUB_WORKSPACE/AutomacaoWeb/tests/*.robot
    # Etapa de geração de um report personalizado
    - name: Download robotmetrics
      if: always()
      run: |
        cd results
        robotmetrics -M regression_metrics.html
    # Etapa de publicação do report em uma pasta no projeto chamada results
    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robot-test-results
        path: results
      
