name: Robot CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: local
      run: ls $GITHUB_WORKSPACE/AutomacaoWeb/tests/
    - name: Robot Framework - Tests
      run: robot $GITHUB_WORKSPACE/AutomacaoWeb/tests/*.robot
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: surefire-reports
        path: ./target/surefire-reports/**
    # - name: Robot Framework
    #   uses: joonvena/robotframework-docker-action@v1.1
    #   with:
    #     robot_tests_dir: $GITHUB_WORKSPACE/AutomacaoWeb/tests/
    # #     # robot_reports_dir: './reports'
    
          
